Scrape test (#304)

diff --git a/.github/workflows/scrape.yml b/.github/workflows/scrape.yml
--- a/.github/workflows/scrape.yml
+++ b/.github/workflows/scrape.yml
@@ -28,6 +28,15 @@ jobs:
 
       - name: Run Scrape on ${{ github.event.inputs.term }}
         run: >
-          ./websocat
+          exec ./websocat
           "wss://nyu.a1liu.com/api/scrape/${{ github.event.inputs.term }}?source=${{ github.event.inputs.source }}"
           -n --basic-auth "${{ secrets.SCHEDGE_PASSWORD }}"
+          | tee output.txt
+
+      - name: Check for success
+        run: |
+          output=$(tail output.txt)
+          if [[ "$output" =~ "Failed: ".* ]]; then
+            echo "Scraping failed"
+            exit 1
+          fi
